services:
  db:
    image: postgres:latest
    env_file: ./.env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/00-schema.sql
      - ./database/seed.sql:/docker-entrypoint-initdb.d/01-seed.sql

volumes:
  postgres_data:
